version: '3'
services:
  multi-git-dashboard:
    build: 
      context: .
      dockerfile: ./multi-git-dashboard/Dockerfile
    networks:
      - app-network
  
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - /home/sadm/Repositories/:/app/repositories
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - multi-git-dashboard
      - backend
    networks:
      - app-network

  mongo:
    build: ./mongo
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - './data:/data/db'
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge