version: '3'
services:
  multi-git-dashboard:
    build: 
      context: .
      dockerfile: ./multi-git-dashboard/Dockerfile
    networks:
      - app-network
  
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - multi-git-dashboard
      - backend
    networks:
      - app-network

  mongo:
    build: ./mongo
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - './data:/data/db'

networks:
  app-network:
    driver: bridge